#!/bin/bash
HOST_LIST=(
"10.60.1.144"  
"10.61.1.144"
)

echo ----------------------quick ssh-----------------------------
echo ${#HOST_LIST[@]} hosts in list
index=1

for host in ${HOST_LIST[@]}; do
    echo [$index] $host
    index=$(($index+1))
done

echo ------------------------------------------------------------
echo -n "Enter a number: " 
read x
x=$(($x-1))
ssh root@${HOST_LIST[$x]}
