set nu
syntax enable
syntax on
set nocompatible
set background=dark
set shiftwidth=4
set tabstop=4
set smarttab
set expandtab
set smartindent
set autoindent
set foldlevel=100
set hlsearch
set ignorecase
set laststatus=2
set mouse=a
set so=10 "光标上下移动时保持10行
set t_Co=256
set wildmenu " 按tab键提示的时候会列出所有的选择
set hid
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set nobackup
set nowb
set noswapfile
map j gj
map k gk

" 各种插件
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'fatih/vim-go'
Bundle 'dgryski/vim-godef'
Bundle 'Blackrush/vim-gocode'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'vim-scripts/taglist.vim'
call vundle#end()
filetype plugin indent on

" 重新打开文件，光标定位到上次退出时的位置
if has("autocmd")
	  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

let g:godef_same_file_in_same_window=1

" 关于YouCompleteMe插件的配置
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"
let g:ycm_auto_trigger = 1
let g:ycm_show_diagnostics_ui = 0
let g:ycm_autoclose_preview_window_after_completion = 1

" 关于airline插件的配置
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" taglist 配置
let Tlist_File_Fold_Auto_Close = 1
let Tlist_Show_One_File = 1
let Tlist_Sort_Type ='name'
let Tlist_Exit_OnlyWindow = 1
let Tlist_WinWidth = 32
let Tlist_Use_Right_Window = 1
if has('mac')
let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
elseif has('unix')
let Tlist_Ctags_Cmd="/usr/bin/ctags"
endif
map <F1> :TlistToggle <CR>

" 关于ctrlp的配置
" let g:ctrlp_working_path_mode = 'ra'
" set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " Linux/MacOSX
" let g:ctrlp_user_command = 'find %s -type f'        " MacOSX/Linux

" 以下为按键映射
let mapleader = "-"
" let mapleader = "\<F2>"

" 修改和重新加载.vimrc
nnoremap <leader>ev :sp $MYVIMRC<cr>:nohl<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>:nohl<cr>

" inoremap <leader>y <esc>kyypi
nnoremap <leader>y <esc>kyyp

" tab键缩进
vnoremap <TAB> >
vnoremap <S-TAB> <

" 空格折叠
noremap <space> za

" 切换窗口
nnoremap <leader>h <c-w>h
nnoremap <leader>j <c-w>j
nnoremap <leader>k <c-w>k
nnoremap <leader>l <c-w>l
nnoremap <leader><left> <c-w>h
nnoremap <leader><down> <c-w>j
nnoremap <leader><up> <c-w>k
nnoremap <leader><right> <c-w>l

" 切换buffer
nnoremap <leader>1 1gt<cr>
nnoremap <leader>2 2gt<cr>
nnoremap <leader>3 3gt<cr>
nnoremap <leader>4 4gt<cr>
nnoremap <leader>5 5gt<cr>
nnoremap <leader>6 6gt<cr>
nnoremap <leader>7 7gt<cr>
nnoremap <leader>8 8gt<cr>
nnoremap <leader>9 9gt<cr>


nnoremap <leader>b :ls<cr>

" 切换两次上次打开的文件
nnoremap <leader><tab> <c-^>

" autocmd vimenter * NERDTree
noremap <F2> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

autocmd FileType c source ~/.vim/cpp.vim
autocmd FileType cpp source ~/.vim/cpp.vim
autocmd FileType python source ~/.vim/py.vim
autocmd FileType go source ~/.vim/go.vim
